language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build-storybook
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master
deploy:
  provider: npm
  skip_cleanup: true
  api_key: $npm_token
  email: $npm_token
  on:
    branch: master
  